spring.application.name=Inventario-TI

spring.datasource.url=jdbc:postgresql://${RDS_ENDPOINT}:5432/inventario
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

flyway.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.token.secret= ${JWT_SECRET:my-secret-key}

spring.ai.openai.api-key=AIzaSyAXQY91O-zhqe5cYPKrfTC4t1RqmDuGuDA
