CREATE TABLE USU_MAQ_SOFT_PIP(
	ID_USU_MAQ_SOFT_PIP SERIAL NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_SOFTWARE INT NOT NULL,
	ID_MAQUINA INT UNIQUE NOT NULL,
	ID_PIP INT NOT NULL,
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_USU_MAQ_SOFT_PIP),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_SOFTWARE) REFERENCES SOFTWARE(ID_SOFTWARE),
	FOREIGN KEY(ID_MAQUINA) REFERENCES MAQUINA(ID_MAQUINA),
	FOREIGN KEY(ID_PIP) REFERENCES PIP(ID_PIP)
);

INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (1, 5, 1, 2);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (2, 2, 2, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (3, 2, 3, 3);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (4, 3, 4, 5);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (5, 7, 5, 6);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (6, 10, 6, 2);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (7, 6, 7, 4);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (8, 2, 8, 10);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (9, 11, 9, 8);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (10, 9, 10, 9);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (11, 5, 11, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (12, 8, 12, 3);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (13, 2, 13, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (14, 2, 14, 5);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (15, 7, 15, 6);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (16, 12, 16, 7);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (17, 1, 17, 4);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (18, 4, 18, 2);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (19, 11, 19, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (20, 3, 20, 3);