ALTER TABLE USUARIO_SISTEMA
ADD COLUMN ID_DEPARTAMENTO INTEGER;

ALTER TABLE USUARIO_SISTEMA
ADD CONSTRAINT fk_usuario_departamento
FOREIGN KEY (ID_DEPARTAMENTO)
REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO);

ALTER TABLE USUARIO_SISTEMA
ADD COLUMN DATA_CADASTRO TIMESTAMP;