---- Remove a foreign key antiga que apontava para a tabela USUARIO
--ALTER TABLE USU_MAQ_SOFT_PIP
--DROP CONSTRAINT usu_maq_soft_pip_id_usuario_fkey;
--
---- Renomeia a coluna para refletir a nova entidade UsuarioSistema
--ALTER TABLE USU_MAQ_SOFT_PIP
--RENAME COLUMN ID_USUARIO TO ID_USUARIO_SISTEMA;
--
---- Cria nova foreign key para a tabela USUARIO_SISTEMA
--ALTER TABLE USU_MAQ_SOFT_PIP
--ADD CONSTRAINT fk_usu_maq_soft_pip_usuario_sistema
--FOREIGN KEY (ID_USUARIO_SISTEMA)
--REFERENCES USUARIO_SISTEMA(ID_USUARIO_SISTEMA);


ALTER TABLE USU_MAQ_SOFT_PIP
DROP CONSTRAINT IF EXISTS usu_maq_soft_pip_id_usuario_fkey;

-- Apaga todos os dados da tabela para evitar violação de FK
DELETE FROM USU_MAQ_SOFT_PIP;

-- Renomeia a coluna para refletir a nova referência à tabela USUARIO_SISTEMA
ALTER TABLE USU_MAQ_SOFT_PIP
RENAME COLUMN ID_USUARIO TO ID_USUARIO_SISTEMA;

-- Cria nova foreign key para a tabela USUARIO_SISTEMA
ALTER TABLE USU_MAQ_SOFT_PIP
ADD CONSTRAINT fk_usu_maq_soft_pip_usuario_sistema
FOREIGN KEY (ID_USUARIO_SISTEMA)
REFERENCES USUARIO_SISTEMA(ID_USUARIO_SISTEMA);

INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (1, 5, 1, 2);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (2, 2, 2, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (3, 2, 3, 3);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (4, 3, 4, 5);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (5, 7, 5, 6);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (6, 10, 6, 2);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (7, 6, 7, 4);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (8, 2, 8, 10);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (9, 11, 9, 8);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (10, 9, 10, 9);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (11, 5, 11, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (12, 8, 12, 3);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (13, 2, 13, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (14, 2, 14, 5);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (15, 7, 15, 6);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (16, 12, 16, 7);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (17, 1, 17, 4);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (18, 4, 18, 2);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (19, 11, 19, 1);
INSERT INTO USU_MAQ_SOFT_PIP (ID_USUARIO_SISTEMA, ID_SOFTWARE, ID_MAQUINA, ID_PIP) VALUES (20, 3, 20, 3);