CREATE TABLE PRIORIDADE(
	ID_PRIORIDADE SERIAL NOT NULL,
	NIVEL_PRIORIDADE VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID_PRIORIDADE)
);

INSERT INTO PRIORIDADE (NIVEL_PRIORIDADE) VALUES ('BAIXO');
INSERT INTO PRIORIDADE (NIVEL_PRIORIDADE) VALUES ('MEDIO');
INSERT INTO PRIORIDADE (NIVEL_PRIORIDADE) VALUES ('ALTO');