CREATE TABLE STATUS(
	ID_STATUS SERIAL NOT NULL,
	VALOR_STATUS VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID_STATUS)
);

INSERT INTO STATUS (VALOR_STATUS) VALUES ('EM ABERTO');
INSERT INTO STATUS (VALOR_STATUS) VALUES ('EM TRATATIVA');
INSERT INTO STATUS (VALOR_STATUS) VALUES ('RESOLVIDO');