CREATE TABLE USUARIO(
	ID_USUARIO SERIAL NOT NULL,
	NOME_USUARIO VARCHAR(255) NOT NULL,
	ID_DEPARTAMENTO INT NOT NULL,
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (ID_USUARIO),
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('João Silva', 2);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Maria Oliveira', 1);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Carlos Pereira', 3);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Ana Costa', 4);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Pedro Martins', 5);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Sofia Ferreira', 2);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Lucas Rodrigues', 6);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Julia Almeida', 7);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Bruno Gomes', 5);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Camila Lima', 3);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Rafael Souza', 2);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Larissa Santos', 4);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Gustavo Ribeiro', 3);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Beatriz Alves', 1);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Matheus Carvalho', 5);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Isabela Mendes', 6);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Felipe Barros', 7);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Gabriela Rocha', 2);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Vinicius Nogueira', 5);
INSERT INTO USUARIO (NOME_USUARIO, ID_DEPARTAMENTO) VALUES ('Manuela Pinto', 4);