CREATE TABLE SOFTWARE(
	ID_SOFTWARE SERIAL NOT NULL,
	NOME_SOFTWARE VARCHAR(100) NOT NULL,
	SERIAL_SOFTWARE VARCHAR(100) NOT NULL,
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(ID_SOFTWARE)
);

INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Microsoft Windows 11 Pro', 'AAAAA-BBBBB-CCCCC-DDDDD-EEEEE');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Microsoft Office 365', 'FOO365-BAR123-BAZ456-QUX789');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Adobe Photoshop CC', 'ADBE-1234-5678-9012-3456-7890');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('AutoCAD 2024', 'ACAD-PRO-X2Y4-Z6A8-B1C3');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Visual Studio Code', 'VSCD-OPEN-SOUR-CE00-FREE');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('7-Zip', '7ZIP-FREE-WARE-COMP-RESS');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Slack', 'SLACK-TEAM-COMM-PROD-TIVE');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Figma', 'FIGMA-DESIGN-COLLAB-CLOUD');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Oracle Database 21c', 'ORCL-DB-ENT-21C-L1CENSE');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('VMware vSphere', 'VMW-VSPH-ENTP-LUS-KEY01');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Tableau Desktop', 'TAB-DPRO-2023-VIZ-DATA');
INSERT INTO SOFTWARE (NOME_SOFTWARE, SERIAL_SOFTWARE) VALUES ('Notepad++', 'NPP-FREE-EDITOR-TEXT-CODE');