CREATE TABLE TIPO_MARCA_PROCESSADOR(
	ID_MARCA_PROCESSADOR SERIAL NOT NULL,
	NOME_MARCA_PROCESSADOR VARCHAR(5) NOT NULL,
	PRIMARY KEY(ID_MARCA_PROCESSADOR)
);

INSERT INTO TIPO_MARCA_PROCESSADOR (NOME_MARCA_PROCESSADOR) VALUES ('AMD');
INSERT INTO TIPO_MARCA_PROCESSADOR (NOME_MARCA_PROCESSADOR) VALUES ('INTEL');