CREATE TABLE TIPO_FREQUENCIA_MEMORIA(
	ID_FREQUENCIA_MEMORIA SERIAL NOT NULL,
	FREQUENCIA_MEMORIA VARCHAR(4) NOT NULL,
	PRIMARY KEY(ID_FREQUENCIA_MEMORIA)
);

INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('200');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('266');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('333');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('400');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('533');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('667');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('800');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('1066');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('1333');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('1600');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('1866');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('2133');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('2400');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('2666');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('2933');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('3200');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('4800');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('5200');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('6000');
INSERT INTO TIPO_FREQUENCIA_MEMORIA (FREQUENCIA_MEMORIA) VALUES ('6400');