CREATE TABLE TIPO_UNIDADE_ARMAZENAMENTO(
	ID_TIPO_ARMAZENAMENTO SERIAL NOT NULL,
	TIPO_ARMAZENAMENTO VARCHAR(4) NOT NULL,
	PRIMARY KEY(ID_TIPO_ARMAZENAMENTO)
);

INSERT INTO TIPO_UNIDADE_ARMAZENAMENTO (TIPO_ARMAZENAMENTO) VALUES ('SSD');
INSERT INTO TIPO_UNIDADE_ARMAZENAMENTO (TIPO_ARMAZENAMENTO) VALUES ('HDD');
INSERT INTO TIPO_UNIDADE_ARMAZENAMENTO (TIPO_ARMAZENAMENTO) VALUES ('NVME');